server:
  port: 8081

spring:
  application:
    name: springcloudtest
  profiles:
      active: test
  redis:
    database: 0
    host: 192.168.246.180
    port: 6379
    timeout: 100
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0




mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

conf:
  name: gf

url:
   queryUrl: www.baidu.com?name="hahah"