server:
  port: 8082

spring:
#  自定义装配
  user:
    enabled: true
    name: gf666
  application:
    name: springcloudtest
  datasource: #定义数据源
      name: tkTest
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://192.168.246.180:3306/tkTest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root  #数据库用户名，root为管理员
      password: root  #该数据库用户的密码
      driver-class-name: com.mysql.cj.jdbc.Driver
      #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
      #useSSL也是某些高版本mysql需要问有没有用SSL连接
  cache:
    type: redis
  redis:
      database: 0
      host: 192.168.246.180
      port: 6379
      timeout: 1000
      lettuce:
        pool:
          max-active: 100
          max-wait: 1000
          max-idle: 50
          min-idle: 0
        shutdown-timeout: 100
      password:

mybatis:
  type-aliases-package: com.springcloudtest.domain
  mapper-locations: classpath:mapper/*Mapper.xml

url:
  queryUrl: www.baidu.com
