server:
  port: 8082

spring:
  application:
    name: springcloudtest

  redis:
      database: 0
      host: 192.168.246.180
      port: 6379
      timeout: 10000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
